[package]
name = "chainbridgex"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.15", features = ["full"] }
warp = "0.3"
rand = "0.8"
sha2 = "0.9"
log = "0.4"
env_logger = "0.9"

[dependencies.rusqlite]
version = "0.27.2"
features = ["serde_json"]
